# Auto-generated configuration variables
# Do not edit this file directly, modify config.yaml instead

import yaml
import os

# Load configuration from YAML file
_config_dir = os.path.dirname(os.path.abspath(__file__))
_config_path = os.path.join(_config_dir, 'config.yaml')

try:
    with open(_config_path, 'r') as f:
        _config = yaml.safe_load(f)
except FileNotFoundError:
    raise FileNotFoundError(f"Configuration file not found at {_config_path}")
except yaml.YAMLError as e:
    raise ValueError(f"Error parsing YAML file: {e}")

# ROS Topic Names
ROSTOPIC_STEREO_LEFT = _config["topics"]["stereo_left"]
ROSTOPIC_STEREO_RIGHT = _config["topics"]["stereo_right"]
ROSTOPIC_FS_DEPTH = _config["topics"]["fs_depth"]
ROSTOPIC_RS_DEPTH = _config["topics"]["rs_depth"]
ROSTOPIC_COLOR = _config["topics"]["color"]
ROSTOPIC_POINTCLOUD = _config["topics"]["pointcloud"]

# Frame Configuration
PCD_FRAME = _config["frames"]["pcd_frame"]

# Extrinsics
EXTRINSICS_VALUES = _config["extrinsics"]["values"]

# Processing Configuration
PROCESSING_SCALE = _config["processing"]["scale"]
TIMER_DURATION = _config["processing"]["timer_duration"]

# Camera Configuration
CAMERA_SERIAL_NO = _config["camera"]["serial_no"]

# Network Configuration
ROS_HOSTNAME = _config["network"]["ros_hostname"]
ROS_IP = _config["network"]["ros_ip"]
ROS_MASTER_URI = _config["network"]["ros_master_uri"]

# Docker Configuration
DOCKER_IMAGE_NAME = _config["docker"]["image_name"]
DOCKER_CUDA_IMAGE = _config["docker"]["cuda_image"] 